services:
  contenedor-principal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contenedor-principal
    ports:
      - "3000:3000"
      - "8545:8545"  # Opcional, solo si necesitas exponer el puerto de Hardhat
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true  # Enable interactive input
    tty: true         # Allocate pseudo-TTY
    networks:
      - blockchain-network

networks:
  blockchain-network:
    driver: bridge